#!/bin/bash
############################
# Script for setting up stuff
############################

## Variables

dir=~/dotfiles          # dotfiles directory
olddir=~/dotfiles_backup   # old dotfiles backup directory

# list of files/folders to symlink in homedir
files="vimrc tmux.conf zshrc"

## Scripts

# Create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# Change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# Move any existing dotfiles in homedir to dotfiles_old directory, then
# create symlinks 
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file
done

# Install Plug
echo "Installing Plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "...done"

# Install other vim plugins
echo "Installing Vim plugins"
vim +PlugInstall! +qall
echo "...done"
